version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@1.8.2

executors:
  golang:
    docker:
      - image: circleci/golang:1.11
  gcloud:
    docker:
      - image: google/cloud-sdk:latest

jobs:
  deploy:
    executor: gcloud
    steps:
      - checkout
      - gcp-cli/initialize
      - run: gcloud functions deploy bot --quiet --runtime go111 --trigger-http --entry-point BotEndpoint --memory 128MB --region asia-northeast1 --set-env-vars BOT_VERIFICATION_TOKEN=$BOT_VERIFICATION_TOKEN,BOT_ACCESS_TOKEN=$BOT_ACCESS_TOKEN,BOT_SYSTEM_MESSAGE_CHANNEL_ID=$BOT_SYSTEM_MESSAGE_CHANNEL_ID,TRAQ_ORIGIN=$TRAQ_ORIGIN

workflows:
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
