name: release

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deploy
      uses: google-github-actions/deploy-cloud-functions@main
      with:
        name: bot
        runtime: go113
        entry_point: BotEndpoint
        memory_mb: 128
        region: asia-northeast1
        credentials: ${{ secrets.GCP_SA_KEY }}
        env_vars: BOT_VERIFICATION_TOKEN=${{ secrets.BOT_VERIFICATION_TOKEN}},BOT_ACCESS_TOKEN=${{ secrets.BOT_ACCESS_TOKEN }},BOT_SYSTEM_MESSAGE_CHANNEL_ID=${{ secrets.BOT_SYSTEM_MESSAGE_CHANNEL_ID }},TRAQ_ORIGIN=${{ secrets.TRAQ_ORIGIN }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
